using System;

namespace Screenbox.Core.Helpers;

/// <summary>
/// Helper methods to detect precision touchpad wheel input using delta heuristics.
/// </summary>
public static class TouchpadHelper
{
    private const int WheelDelta = 120;
    private const long GestureTimeoutMs = 300;

    [ThreadStatic]
    private static long _lastTouchpadScrollTimestamp;

    /// <summary>
    /// Determines whether the given mouse wheel delta was generated by a precision touchpad gesture.
    /// </summary>
    /// <remarks>
    /// Traditional physical mouse wheels scroll in discrete notches that emit multiples of 120 (e.g. ±120, ±240).
    /// Precision touchpads emit continuous, fine-grained deltas (often |delta| &lt; 120 or delta % 120 != 0).
    /// If an event within a stream of touchpad inputs happens to land on an exact multiple of 120 (e.g. during a fast flick),
    /// it is still recognized as touchpad input if received within <see cref="GestureTimeoutMs"/> of a preceding granular delta.
    /// </remarks>
    /// <param name="delta">The pointer wheel delta value.</param>
    /// <returns><see langword="true"/> if the delta appears to originate from a touchpad gesture; otherwise, <see langword="false"/>.</returns>
    public static bool IsTouchpadDelta(int delta)
    {
        if (delta == 0) return false;

        long now = Environment.TickCount64;
        bool isGranularDelta = Math.Abs(delta) < WheelDelta || delta % WheelDelta != 0;

        if (isGranularDelta)
        {
            _lastTouchpadScrollTimestamp = now;
            return true;
        }

        if (now - _lastTouchpadScrollTimestamp < GestureTimeoutMs)
        {
            _lastTouchpadScrollTimestamp = now;
            return true;
        }

        return false;
    }

    /// <summary>
    /// Determines whether the given mouse wheel delta was generated by a precision touchpad gesture.
    /// </summary>
    /// <param name="delta">The pointer wheel delta value as a double.</param>
    /// <returns><see langword="true"/> if the delta appears to originate from a touchpad gesture; otherwise, <see langword="false"/>.</returns>
    public static bool IsTouchpadDelta(double delta) => IsTouchpadDelta((int)Math.Round(delta));

    /// <summary>
    /// Resets the internal touchpad gesture timer. Intended for testing.
    /// </summary>
    public static void Reset()
    {
        _lastTouchpadScrollTimestamp = 0;
    }
}
