pull_request_title: 'l10n: Crowdin updates'
pull_request_labels:
  - crowdin
  - l10n
files:
  - source: /Screenbox/Strings/en-US/*.resw
    ignore:
      - /Screenbox/Strings/en-US/Keyboard*.resw
    translation: /Screenbox/Strings/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /Screenbox/Strings/en-US/*.md
    translation: /Screenbox/Strings/%locale%/%original_file_name%
    update_option: update_as_unapproved
