namespace Screenbox.Core.Enums
{
    public enum ResourceName
    {
        PropertyTitle,
        PropertySubtitle,
        PropertyYear,
        PropertyProducers,
        PropertyWriters,
        PropertyLength,
        PropertyResolution,
        PropertyBitRate,
        PropertyContributingArtists,
        PropertyAlbum,
        PropertyAlbumArtist,
        PropertyGenre,
        PropertyTrack,
        PropertyFileType,
        PropertyContentType,
        PropertySize,
        PropertyLastModified,
        UnknownArtist,
        UnknownAlbum,
        Disable,
        GoToPosition,
        FailedToLoadSubtitleNotificationTitle,
        FailedToSaveFrameNotificationTitle,
        FrameSavedNotificationTitle,
        ResumePositionNotificationTitle,
        VolumeChangeStatusMessage,
        AccessDeniedMusicLibraryTitle,
        AccessDeniedVideosLibraryTitle,
        AccessDeniedPicturesLibraryTitle,
        OpenPrivacySettingsButtonText,
        AccessDeniedMessage
    }
}