<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <SupportedOSPlatformVersion>10.0.18362.0</SupportedOSPlatformVersion>
    <Copyright>Copyright © 2023-2026 Tung Huynh</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Uwp.Animations">
      <Version>8.2.251219</Version>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Uwp.Extensions">
      <Version>8.2.251219</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.UI.Xaml">
      <Version>2.8.7</Version>
    </PackageReference>
  </ItemGroup>
</Project>