using Windows.UI.Xaml.Markup;

namespace Screenbox.Strings;

/*
 * This file contains class stubs for markup extensions generated by ReswPlus.
 * Source generator runs after the XAML precompile step so the generated classes are not
 * available in the XamlTypeInfo, which causes runtime errors when using the extensions in XAML.
 * By defining these stubs, we ensure that the generated extensions are recognized as valid
 * markup extensions during XAML compilation, preventing runtime errors and allowing the
 * application to function correctly. The actual implementation of these extensions will be
 * provided by the ReswPlus source generator at compile time.
 */

public partial class ResourcesExtension : MarkupExtension
{
}

public partial class KeyboardResourcesExtension : MarkupExtension
{
}
