using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Markup;

/*
 * ReswPlus generated MarkupExtensions do not work with Native AOT XAML toolchain.
 * Workaround: Create proxies classes for the auto-generated code until we can figure out a better solution.
 */
namespace Screenbox.Strings;

[MarkupExtensionReturnType(ReturnType = typeof(string))]
public partial class ResourcesProxyExtension : MarkupExtension
{
    private static _ReswPlus_AutoGenerated.ResourceStringProvider _resourceStringProvider;
    static ResourcesProxyExtension()
    {
        _resourceStringProvider = new _ReswPlus_AutoGenerated.ResourceStringProvider("Resources");
    }

    public ResourcesExtension.KeyEnum Key { get; set; }
    public IValueConverter? Converter { get; set; }
    public object? ConverterParameter { get; set; }

    protected override object ProvideValue()
    {
        var value = Key == ResourcesExtension.KeyEnum._Undefined ? "" : _resourceStringProvider.GetString(Key.ToString());
        return Converter is null ? value : Converter.Convert(value, typeof(string), ConverterParameter, null);
    }
}

[MarkupExtensionReturnType(ReturnType = typeof(string))]
public partial class KeyboardResourcesProxyExtension : MarkupExtension
{
    private static _ReswPlus_AutoGenerated.ResourceStringProvider _resourceStringProvider;
    static KeyboardResourcesProxyExtension()
    {
        _resourceStringProvider = new _ReswPlus_AutoGenerated.ResourceStringProvider("KeyboardResources");
    }

    public KeyboardResourcesExtension.KeyEnum Key { get; set; }
    public IValueConverter? Converter { get; set; }
    public object? ConverterParameter { get; set; }

    protected override object ProvideValue()
    {
        var value = Key == KeyboardResourcesExtension.KeyEnum._Undefined ? "" : _resourceStringProvider.GetString(Key.ToString());
        return Converter is null ? value : Converter.Convert(value, typeof(string), ConverterParameter, null);
    }
}
